### PR TITLE
Added SMD USB-micro-B and 0.5mm FFC connectors

### PR DESCRIPTION
**Pull request by zeroping**
Let me know if I should include the python scripts that generated these FFC connectors. It's not uncommon for me to make a script to generate these parts with many pin variations. If you need to make tweaks, or if we wanted to include a directory of scripts to generate some of these footprints, then I can send it over.

### CODE REVIEW

**Comment by ricardocrudo** [comment]
@zeroping because they are a lot of new footprints maybe them should be in a new repository.
About the footprints, you can make a small adjust on FFC_FH* silkscreen line to not touch the pads. 
USB-micro-B also has silkscreen issues.
And finally, all of them need to be fixed to have Normal+Insert attribute.

**Comment by ricardocrudo** [comment]
Actually, JST connectors already has a repo: https://github.com/KiCad/Connectors_JST.pretty

**Comment by pointhi** [comment]
I also would suggest to add the Partnumber to the USB connector name. When a connector has a repository, the PR has to made there.

**Comment by hackscribble** [comment]
Closing and re-opening to trigger Travis checks.

**Comment by robertely** [comment]
Just an FYI `http://www.hirose.co.jp/cataloge_hp/ed_FH34S_20140305.pdf` Doesn't seem to be working.

**Comment by Shackmeister** [comment]
Hi @zeroping 
In case you still want these connectors in the library you should reopen a PR in these libraries:
USB connector: https://github.com/KiCad/Connectors_USB.pretty
JST connector: https://github.com/KiCad/Connectors_JST.pretty
Hirose Connector: https://github.com/KiCad/Connectors_Hirose.pretty

**Pull request closed without merging**
