### PR TITLE
Added Tag-Connect pogo-pin programming connectors

### PR DESCRIPTION
**Pull request by SchrodingersGat**
http://www.tag-connect.com/

**Datasheets**
http://www.tag-connect.com/Materials/TC2030-IDC.pdf
http://tag-connect.com/Materials/TC2030-IDC-NL.pdf
http://www.tag-connect.com/Materials/TC2050-IDC%20Datasheet.pdf
http://www.tag-connect.com/Materials/TC2050-IDC-NL%20Datasheet.pdf

**KLC**
These violate rule 10.5 as they are set as "virtual" components (they have no component associated, they are copper only)

**Example**

Example of the four footprints on a PCB. The pads are removed from the paste layer as they need to remain exposed.
fp

### CODE REVIEW

**Comment by pointhi** [comment]
From what I see, the pads have no holes -> not usable for this connectors.

**Comment by SchrodingersGat** [comment]
That's just a trick of the rendering:

![how-do-you-like-them-holes]https://cloud.githubusercontent.com/assets/10080325/15677247/cc850800-278c-11e6-9da6-4a190fe6dae6.png)

mod

**Comment by pointhi** [comment]
I'm pretty sure this is not a rendering bug.

When you look into the file, you will find out, there are no drill sizes specified for the pads.

**Comment by SchrodingersGat** [comment]
The pads are SMT only - the NPTH holes are for alignment of the connector which has spring-loaded pins which press onto the SMT pads.

Ref http://www.tag-connect.com/sites/default/files/images/ddblock/1tag.jpg

(Unless I'm misreading your comment?)

**Comment by bobc** [comment]
The footprints look ok to me. The contact pads should be SMD not through-hole, this is the standard method for "pogo" type connectors or ICT test points.

**Comment by SchrodingersGat** [comment]
@jkriege2 this one has been sitting around for a while - can you check over this when you get a chance?

**Comment by jkriege2** [comment]
Hi!

only two minor things to fix:
1. check linewidth on F.SilkS as it is 0.15mm in some cases
2. add REFDES/%R to F.Fab
3. My script proposes slightly larger courtyards (optional, I will merge when 1+2 are fixed):
```
checking module: Tag-Connect_TC2030-IDC-FP
  Violating Rule 10.5
    Reference designator has a height of 1mm or smaller if needed, thickness of 0.15mm and is placed on
    the silkscreen and the fabrication layer.
      Reference label should also be available on layer 'F.Fab'.

  Violating Rule 6.5
    Silkscreen is not superposed to pads, its outline is completely visible after board assembly, uses
    0.12mm line width and provides a reference mark for pin 1. (IPC-7351C).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'width': 0.15, 'layer':
      'F.SilkS', 'start': {'x': -1.905, 'y': 1.27}, 'end': {'x': -1.905, 'y': 0.635}}).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'width': 0.15, 'layer':
      'F.SilkS', 'start': {'x': -1.27, 'y': 1.27}, 'end': {'x': -1.905, 'y': 1.27}}).

  Violating Rule 6.6
    Courtyard line has a width 0.05mm. This line is placed so that its clearance is measured from its
    center to the edges of pads and body, and its position is rounded on a grid of 0.01mm.
      For this footprint a rectangular courtyard {'width': 7.77, 'x': -4.23, 'height': 8.46, 'y': -4.23}
      was expected, but a courtyard rectangle {'width': 8.0, 'x': -4.25, 'height': 8.5, 'y': -4.25} was
      found

checking module: Tag-Connect_TC2030-IDC-NL
  Violating Rule 10.5
    Reference designator has a height of 1mm or smaller if needed, thickness of 0.15mm and is placed on
    the silkscreen and the fabrication layer.
      Reference label should also be available on layer 'F.Fab'.

  Violating Rule 6.5
    Silkscreen is not superposed to pads, its outline is completely visible after board assembly, uses
    0.12mm line width and provides a reference mark for pin 1. (IPC-7351C).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'width': 0.15, 'layer':
      'F.SilkS', 'start': {'x': -1.905, 'y': 1.27}, 'end': {'x': -1.905, 'y': 0.635}}).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'width': 0.15, 'layer':
      'F.SilkS', 'start': {'x': -1.27, 'y': 1.27}, 'end': {'x': -1.905, 'y': 1.27}}).

  Violating Rule 6.6
    Courtyard line has a width 0.05mm. This line is placed so that its clearance is measured from its
    center to the edges of pads and body, and its position is rounded on a grid of 0.01mm.
      For this footprint a rectangular courtyard {'width': 7.08, 'x': -3.54, 'height': 4.03, 'y': -2.02}
      was expected, but a courtyard rectangle {'width': 7.0, 'x': -3.5, 'height': 4.0, 'y': -2} was found


checking module: Tag-Connect_TC2050-IDC-FP
  Violating Rule 10.5
    Reference designator has a height of 1mm or smaller if needed, thickness of 0.15mm and is placed on
    the silkscreen and the fabrication layer.
      Reference label should also be available on layer 'F.Fab'.

  Violating Rule 6.5
    Silkscreen is not superposed to pads, its outline is completely visible after board assembly, uses
    0.12mm line width and provides a reference mark for pin 1. (IPC-7351C).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'width': 0.15, 'layer':
      'F.SilkS', 'start': {'x': -3.175, 'y': 1.27}, 'end': {'x': -3.175, 'y': 0.635}}).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'width': 0.15, 'layer':
      'F.SilkS', 'start': {'x': -2.54, 'y': 1.27}, 'end': {'x': -3.175, 'y': 1.27}}).

  Violating Rule 6.6
    Courtyard line has a width 0.05mm. This line is placed so that its clearance is measured from its
    center to the edges of pads and body, and its position is rounded on a grid of 0.01mm.
      For this footprint a rectangular courtyard {'width': 10.31, 'x': -5.5, 'height': 8.46, 'y': -4.23}
      was expected, but a courtyard rectangle {'width': 10.25, 'x': -5.5, 'height': 8.5, 'y': -4.25} was
      found


checking module: Tag-Connect_TC2050-IDC-NL
  Violating Rule 6.5
    Silkscreen is not superposed to pads, its outline is completely visible after board assembly, uses
    0.12mm line width and provides a reference mark for pin 1. (IPC-7351C).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'width': 0.15, 'layer':
      'F.SilkS', 'start': {'x': -3.175, 'y': 1.27}, 'end': {'x': -3.175, 'y': 0.635}}).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'width': 0.15, 'layer':
      'F.SilkS', 'start': {'x': -2.54, 'y': 1.27}, 'end': {'x': -3.175, 'y': 1.27}}).

  Violating Rule 6.6
    Courtyard line has a width 0.05mm. This line is placed so that its clearance is measured from its
    center to the edges of pads and body, and its position is rounded on a grid of 0.01mm.
      For this footprint a rectangular courtyard {'width': 9.62, 'x': -4.81, 'height': 4.03, 'y': -2.02}
      was expected, but a courtyard rectangle {'width': 9.5, 'x': -4.75, 'height': 4.0, 'y': -2} was found

```

JAN

**Comment by SchrodingersGat** [comment]
I have fixed the silkscreen and added REF** to FAB layer.

I think the courtyard is OK? 

What do you think?

**Comment by jkriege2** [comment]
Yes, I think it's OK!
JAN

PS: Nice work!

**Pull request merged**
