### PR TITLE
microSD_Card_Receptacle_Wurth_693072010801 and KISYS3DMOD

### PR DESCRIPTION
**Pull request by Shackmeister**
microsd_card

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Please address KLC issues for the SD card footprint (KLC issues relating to the ones you have just updated KISYS3DMOD are fine)

**Comment by Shackmeister** [comment]
@SchrodingersGat Should I go with the center of the body or the SMD pads?

**Comment by SchrodingersGat** [comment]
Do you mean for the SD card or other ones too?

**Comment by Shackmeister** [comment]
for the SD card, and I mean if the center of the footprint should be based on the center of the pads or the center of the body

**Comment by SchrodingersGat** [comment]
The [second page of the datasheet](http://katalog.we-online.de/em/datasheet/693072010801.pdf) shows that the pick-and-place origin is in the centre of the body, so you should use that.

**Comment by Shackmeister** [comment]
@SchrodingersGat Alrighty, thats what I went with so it should be ready to merge.
(added a few %R's while I was waiting for your response)
perhaps Travis should test if the Fab layer center matches

**Comment by SchrodingersGat** [comment]
Great, thanks for your contribution!

**Comment by pointhi** [comment]
@SchrodingersGat,

how should we handle the manufacturer name ```Würth``` in KiCad? The german special character ```ü``` should be avoided for the sake of non-german users, but simply using an ```u``` is not correctly to my knowlege. Normally ```ü``` is rewritten as ```ue``` when the character is not available, means the correct ASCII writing of ```Würth``` would be ```Wuerth```.

https://www.we-online.com/web/en/wuerth_elektronik/start.php

**Comment by SchrodingersGat** [comment]
@pointhi I was not aware of this spelling, I've always just used `Wurth`. However we should change to `Wuerth` going forward. 

@Shackmeister if you want to submit a new PR changing this to `Wuerth`, that would be great.

**Pull request merged**
