### PR TITLE
PJ-320E and PJ-320DS 3.5mm headphones with microphone connectors

### PR DESCRIPTION
**Pull request by 4x5dm**
## PJ-320E THT Connector

pj-320e
pj-320e
pj-320e_footprint

## PJ-320DS SMD Connector

pj-320ds
pj-320ds
pj-320d_footprint

Both connectors are available on eBay/AliExpress.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi @4x5dm generally pretty good. 

1. Move the second RefDes on the F.Fab layer inside the footprint
1. Shorten the name, it should not be so descriptive

2017-04-07 22_45_37-footprint editor no active library

**Comment by 4x5dm** [comment]
Done.

**Comment by SchrodingersGat** [comment]
Hi @4x5dm I think the names are more precise as `PJ320D_3.5mm_Jack` - can you change to this form and then I can merge.
Thanks!

**Comment by 4x5dm** [comment]
Done.

**Comment by SchrodingersGat** [comment]
Thanks for the contribution :)

**Pull request merged**
