### PR TITLE
Add Micro USB connector Molex-47346-0001

### PR DESCRIPTION
**Pull request by jjuyon**
Hi,
Addition of a footprint for USB_OTG connector.
3D View is comming

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

please follow KLC for this symbol: https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention + we're working on a newer version with example images ... https://github.com/SchrodingersGat/kicad-library/wiki/KLC

1. Please add component outline of F.Fab (width 0.1mm)
2. please add silkscreen, visible AFTER assembly (width 0.12mm)
3. remove the `Connector_Front_Interface` (you can kee the other one of you like)
4. add Doc and keywords
5. set attribute to SMD
6. set anchor to center between pads
7. add courtyard around the component (0.5mm  offset from pad- and component outline)
8. About 3D model: If you download it from vendor: Ensure/Note which license they give to redistribute it/host it here/copy it. If you make it yourself, please also add the CAD-file you use (at least if using FreeCad)

You can use our check scripts to check some of these rules (use the `-v`-option) and even fix some problems (using `--fix`): https://github.com/KiCad/kicad-library-utils

Best,
JAN

**Comment by jjuyon** [comment]
Ok thanks,
I made the changes:

6. What do you mean by "anchor"? If it is the coordinate (0;0) of the grid, then I moved the component to set it between the pads.
8. You are right the 3D view is from the vendor and I cannot share it.

 Best,
Julien

**Comment by jkriege2** [comment]
Thanks for the changes. Some more please ;-)

1. there should be no silkscreen outside the board? Cannot be printed into thin air ;-)
2. F.Fab outline seems a bit too big for me ... please check against the DS dimensions (5x7.5mm² if I'm not mistaken)
3. Silkscreen should be OUTSIDE F.Fab ... although here it might be OK, as the 3D package is smaller at the bottom
4. Courtyrad should be 0.05mm thick and have an offset/clearance of 0.5mm to pads/outline.

best & Thanks,
JAN

**Comment by jjuyon** [comment]
Ok Thanks,
Changes done,

Best,
Julien

**Comment by jkriege2** [comment]
Hi!

Please extend courtyard outside PCB ...
Otherwise. Very nice and I will merge!

JAN

**Comment by jjuyon** [comment]
It's done

Best
Julien

**Comment by jkriege2** [comment]
2017-02-01 19_06_18-footprint editor no active library

**Comment by jkriege2** [comment]
Oh and please round the couryard line coordinates to 0.01mm ...

PS: you can also use our check-scripts to find and in some cases even fix some of these errors:
https://github.com/KiCad/kicad-library-utils

**Comment by jjuyon** [comment]
Ok I got it.
I fixed the courtyard and ran the _check_kicad_mod.py_ and fixed anchor issue

Best,
Julien

**Comment by jjuyon** [comment]
And by the way, I tried to change the mask clearance to 0.05mm and the check script says "Violation rule 10.7". But why? By default it is set to 0 but actually footprint editor makes it big (0.2mm) and it can be smaller in respect of Fab rules (WEdirekt for example).

Best,
Julien

**Comment by jkriege2** [comment]
If you add `-v` as a command-line option you get a hint why the tool complains!

Rest looks good: Nice work!

One comment: I'm thinking that this should maybe better got to https://github.com/KiCad/Connectors_Molex.pretty ... name can stay as it is. If you repost it there, I'll merge!

best,
JAN

**Comment by jkriege2** [comment]
resubmitted there: https://github.com/KiCad/Connectors_Molex.pretty/issues/33

**Pull request closed without merging**
