### PR TITLE
Fix USB type A connector

### PR DESCRIPTION
**Pull request by aurel32**
The USB type A connector footprint is currently not symmetrical (this
can be seen on the 3D view). It looks like that some pins have been
aligned to a mil grid, while the distance between pins on a USB
connector should be aligned on a metric grid.

Fix this by using setting the distance between been pins 2 and 3 to 2mm
and the distance between pins 1 and 2 and between pins 3 and 4 to 2.5mm.
This matches the distance between signals on a female A connector. Also
slightly change the dimensions of the connector to make it fully
symmetrical.

The changes are small enough so that it does not affect the 3D view (it
even looks better now).

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

nice work!

Since you're at it ... could you also fix the other KLC issues? i.e.:
1. add a `%R` label on F.Fab (overlay with existing REFDES label)
2. add the package outline onto F.Fab (width: 0.1mm)
3. make pad of pin1 rectangular as pin1 marker!

Best,
JAN

**Comment by aurel32** [comment]
Thanks for the review. I have added a second commit to my pull request which should fix the KLC issues.

**Comment by jkriege2** [comment]
Hi!

Usually we have the courtyard a bit closer:
2017-02-20 08_00_29-footprint editor no active library

Also: Please take a second look at your courtyard, it should be 0.5mm set off from outline (on F.Fab) and the pad outside. In you design it was sometimes a bit too far away, sometimes a bit too near. 

There is a python script https://github.com/KiCad/kicad-library-utils which (when run with `--fixmore` ) should fix the courtyard automatically!

Best,
JAN

**Comment by aurel32** [comment]
I have just made the changes wrt courtyard, using check_kicad_mod.py --fixmore. The changes done by the scrupt seems visually fine, and the script doesn't complain about KLC rule 6.6 anymore.

**Comment by jkriege2** [comment]
Could you also move the silkscreen, or is there a reason for the large offset?

**Comment by jkriege2** [comment]
@aurel32 Are you still on this?

**Comment by hackscribble** [comment]
Hi @aurel32 

Since you submitted this PR, changes have been made to `USB_A.kicad_mod`.

If you are still interested in contributing, please open a new pull request (in synch with the current master branch) and check your contribution against the latest KiCad Library Convention here: https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention.

Many thanks

**Pull request closed without merging**
