### PR TITLE
Footprint BC-2002 battery holder

### PR DESCRIPTION
**Pull request by cafee**
Hi,

here's fooprint for BC-2002 battery holder for CR2032 cell.

Footprint is based on this document: http://www.challengeelectronics.com/downloads/battery_accessories/metal_coin/BC-2002.pdf

### CODE REVIEW

**Comment by ricardocrudo** [comment]
hello @cafee. please add courtyard line and set anchor to pin 1.

**Comment by cafee** [comment]
Hi i added courtyard line. And setted anchor to one of THT pins with number 1.  
The're two THT pads numbered 1 because:
  - The battery holder is all metal and soldered into two holes (eg. both are positives)
  - Positive pin is number 1 on battery schematic symbol (device symol library).

If this will be too big problem than tell me and i will change number of one of the THT pins.

**Comment by SchrodingersGat** [comment]
Hi @cafee sorry that this has been neglected. We now have a footprint library specific to battery holders:  https://github.com/KiCad/Battery_Holders.pretty

If you can re-submit the PR there, I'll make sure it gets addressed. Thanks.

**Comment by SchrodingersGat** [comment]
@cafee I am closing this one as it is in the wrong PR. Feel free to resubmit to https://github.com/KiCad/Battery_Holders.pretty thanks!

**Pull request closed without merging**
