### PR TITLE
Added Grove_1x04 connector

### PR DESCRIPTION
**Pull request by penoud**
This connector came from the Chinese online shop SeeedStudio

### CODE REVIEW

**Comment by penoud** [comment]
The 3d part listed in the part comment is currently in a PR in kicad-library.

**Comment by jkriege2** [comment]
Hi!

I'm currently looking into this PR, and first of all: thanks for the contrib. Could you please change the following things:
1. Please add a the outline on the FAB layer (0.1mm thick see https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention)
2. I can't find the datasheet (HTTP error 404) ... could you give a coorect URL?

Best,
JAN

**Comment by penoud** [comment]
I corrected as your comment suggested.

**Comment by penoud** [comment]
Unfortunately the URL was valid but the website remove it. If found a link to stackoverflow instead.

**Comment by jkriege2** [comment]
What about one of these links?
https://statics3.seeedstudio.com/images/opl/datasheet/3470090P1.pdf
https://statics3.seeedstudio.com/images/opl/datasheet/3470120P1.pdf
https://statics3.seeedstudio.com/images/opl/datasheet/3470130P1.pdf
https://statics3.seeedstudio.com/images/opl/datasheet/3470140P1.pdf

All from here:
https://www.seeedstudio.com/opl.html -> Connectors -> page 5,6

About the F.FAB:
1. Please snure to follow the KLC: https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention
2. The F.FAB should show the outline of the package
3. The silkscreen should be (mostly) visible after assembly and be 0.12mm thick.

Here's a connector that (already) follows KLC:
2016-12-25 15_31_43-bibliotheksbrowser connectors_molex https___github com_kicad_connectors_mole


Could you please try and make you footprint follow KLC? Thanks and best,
JAN

**Pull request closed without merging**
