### PR TITLE
PJ31060-I And PJ311 3.5mm SMD Connectors

### PR DESCRIPTION
**Pull request by 4x5dm**
This pull request contains footprints for Mini USB and 3.5mm headphone SMD connectors widely available on eBay and AliExpress. I created them from original drawings in order to use in my projects and I like to contribute them to KiCad community.

jack pj-311d
jack pj-31060

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Please fix Travis errors :)

**Comment by 4x5dm** [comment]
Done.

**Comment by SchrodingersGat** [comment]
Same as with your other PR - please rename more like `PJ-311D_3.5mm_Jack`

**Comment by 4x5dm** [comment]
Fixed.

**Comment by SchrodingersGat** [comment]
Thanks for the contribution

**Pull request merged**
