### PR TITLE
added 6 and 8-pin IDC header

### PR DESCRIPTION
**Pull request by chrisnoisel**
Requested by @matthijskooijman ([https://github.com/KiCad/Connectors.pretty/pull/33#issuecomment-263117077](https://github.com/KiCad/Connectors.pretty/pull/33#issuecomment-263117077))

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!
thanks for the contribution.

in principle this looks good, when comparing to the other IDC-footprint, BUT:
We have a set of rules for this lib (KLC, see https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention), which states that there should be the outline of the package on the F.FAB-layer (linewidth 0.1mm) and the silkscreen should be visible also after assembly (width: 0.12mm). Could you change the footprints to match these requirements?

Thanks,
JAN

PS: There are also scripts to check the KLC: https://github.com/KiCad/kicad-library-utils

**Comment by chrisnoisel** [comment]
KLC reported by script/corrected :

- 6.5 : 0.12mm width fixed
- 6.6 : I think it's a bug, end of lines are checked on a 0.05mm grid instead of 0.01mm. Will push a pull-request soon
- 6.7 : not reported by script but I noticed connectors have a 0.5mm gap so I updated all the other IDC_Header as well.

**Comment by jkriege2** [comment]
Silkscreen ... look good. Please add the package outline to F.FAB-layer (linewidth 0.1mm)

best,
JAN

**Comment by chrisnoisel** [comment]
Ah yes, sorry.
I'm not sure what the outline should be, can it match the outer line of the silkscreen ? Like this :
fab

**Comment by jkriege2** [comment]
The outline on F.Fab should reproduce the ACTUAL circumference of the package
The silkscreen should be (mostly) visible after assembling the PCB, i.e. it is usually a bit offset from the F.Fab-line. An example:
2016-12-04 22_59_49-footprinteditor keine aktive bibliothek

**Pull request closed without merging**
