### PR TITLE
added pin-header symbols for 3-pin and 4-pin Fan connectors, as used on PC mainboards

### PR DESCRIPTION
**Pull request by jkriege2**
- see http://www.formfactors.org/developer%5Cspecs%5Crev1_2_public.pdf for details on the 4-pin package
- the 3pin-package is based on this.
- I aso added a motors symbol library, which uses these footprints: KiCad/kicad-library#717
- for 3D models see: https://github.com/KiCad/kicad-library/pull/725

3pin
4pin

fanpin3
fanpin4

### CODE REVIEW

**Comment by jkriege2** [comment]
KLCs check out now ... 3D symbols should be fine too (see https://github.com/KiCad/kicad-library/pull/725)

Can be merged?

best,
JAN

**Comment by SchrodingersGat** [comment]
Jan looking at those 3D models, these look like the Molex KK series, perhaps? 

Do you know specifically what these connectors are? I think they could be added somewhere less generic...

**Comment by jkriege2** [comment]
They are not the same ... observe the psoition of the nibble on the image below (especially for the 4-pin connector)

2017-02-25 18_08_47-pcbnew d__kicad_kicad-library-review-project_kicad-library-review kicad_pcb

**Comment by jkriege2** [comment]
PS: I just noted that I accidentally deleted my branch, so I will close this and push a second PR: https://github.com/KiCad/Connectors.pretty/pull/62

**Pull request closed without merging**
