### PR TITLE
Added SMA6251A13G50 symbol

### PR DESCRIPTION
**Pull request by ondra6ak**
Added symbol for SMA6251A13G50 sma connector

### CODE REVIEW

**Comment by CarlPoirier** [comment]
Hi,

Please review the KiCad Library Convention section 6 here: https://github.com/KiCad/kicad-library/blob/master/KiCad_Library_Convention.txt

Your footprint needs to be fixed before it can be pulled in.

Thanks!

**Comment by bobc** [comment]
KLC has moved to https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention#6-general-rules-for-footprints

**Comment by hackscribble** [comment]
Closing and re-opening to generate Travis checks.

**Comment by hackscribble** [comment]
Source repository was deleted.  Unable to reopen.

**Pull request closed without merging**
