### PR TITLE
USB Mini-B through hole vertical and horizontal connectors

### PR DESCRIPTION
**Pull request by 4x1md**
The request contains USB connectors which are available on eBay/AliExpress. I made these footprints for myself and would like to share them.

## Horizontal

usb_mini_horizontal

## Vertical

usb_mini_vertical

### CODE REVIEW

**Comment by pointhi** [comment]
There exists a special repository for USB connectors: https://github.com/KiCad/Connectors_USB.pretty

Also note, the models you added cannot easily be used by others, because there is no reference to a datasheet, manufactur part number,... .

Footprints of USB connectors have quite some differences, so we need to carefully track properties which can be used by users to find the respective part. ```USB_Mini-B_THT_Horizontal``` is way to general.

**Comment by 4x5dm** [comment]
The problem with these connectors is that I don't have part numbers and don't know how to find them. These are generic connectors which can be bought cheap on eBay/AliExpress. Here are two random examples:

- horizontal: http://www.ebay.com/itm/141788013470
- vertical: http://www.ebay.com/itm/141787599373

**Comment by pointhi** [comment]
@SchrodingersGat: how should we proceed with part's of unknow manufactur

**Comment by SchrodingersGat** [comment]
Initial thought is to add suffix `_Generic` but what happens when a different generic connector is added? I dare say we could find lots of subtle variants on eBay? Or are all these manufactured to the same standards?

The vertical one linked seems very similar to [this one](http://www.cypressindustries.com/pdf/CCMUSBB-32005-85.pdf) - but not identical.

**Comment by SchrodingersGat** [comment]
@4x5dm can you please try and find a datasheet for this? Having an uncharacterised footprint like this in the libraries is not super helpful if people want to find and use it...

**Comment by 4x5dm** [comment]
OK, I'll try.
Could you review my other pull requests (#71, #72 , #73)?

**Comment by 4x5dm** [comment]
The horizontal connector looks like OMRON XM7D-0512:
http://www.mouser.com/ds/2/307/XM7_1113-272863.pdf

PCB layouts are the same.

**Comment by 4x5dm** [comment]
The vertical one is very similar to these

### TMU-02-B-04-N01
http://www.trontek.com.tw/files/15-1317-27935,c4437-1.php

### Mini USB 2.0 Type B Vertical 5 Contacts WR-COM
http://katalog.we-online.de/en/em/COM_MINI_TYPE_B_VERTICAL
(Here I don't see anything similar to part number.)

**Comment by jkriege2** [comment]
I would propose leaving the name as is .... if there's no manufacturer, this HAS to be somehow generic (and I think this footprint should be compatible with many available connectors) ;-) .... but add at least one datasheet link to the description of each footprint.

Finally this should definitely go to the lib https://github.com/KiCad/Connectors_USB.pretty

@pointhi @SchrodingersGat What do you think?

Best,
JAN

**Comment by 4x5dm** [comment]
So should I move this PR to [Connectors_USB.pretty](https://github.com/KiCad/Connectors_USB.pretty)?

**Comment by jkriege2** [comment]
yes please!

Thanks,
JAN

**Comment by poeschlr** [comment]
@4x5dm are you still working on this?

**Comment by 4x5dm** [comment]
Yes

On Jul 26, 2017 12:58 PM, "Rene Pöschl" <notifications@github.com> wrote:

@4x5dm <https://github.com/4x5dm> are you still working on this?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/KiCad/Connectors.pretty/pull/74#issuecomment-318008152>,
or mute the thread

**Comment by 4x5dm** [comment]
Yes

**Comment by Shackmeister** [comment]
Hi @4x1md 
If you want to continue with these footprint you should reopen the PR over at this repo:
https://github.com/KiCad/Connectors_USB.pretty

**Pull request closed without merging**
