### PR TITLE
add footprint for CUI PD-30 connector

### PR DESCRIPTION
**Pull request by ppelleti**
This adds a footprint for the [PD-30](http://www.cui.com/product/resource/pd-30.pdf) connector, meant to be used with [this schematic symbol](https://github.com/KiCad/kicad-library/pull/1485).

pd-30-footprint

### CODE REVIEW

**Comment by hackscribble** [comment]
Posting screenshot from vendor's 3D model for reference.

image

**Comment by hackscribble** [comment]
Hi @ppelleti 

Thanks for the further contribution.

Did you choose circular pads and holes throughout because your PCB manufacturer has problems with oval slots in oval pads?

**Comment by ppelleti** [comment]
> Did you choose circular pads and holes because your PCB manufacturer has problems with oval slots in oval pads?

Yes, I'm using [OSH Park](https://forum.kicad.info/t/oval-pads-not-possible-for-oshpark/835).

**Comment by hackscribble** [comment]
Thanks.

Posting footprint from datasheet for reference.

image

**Comment by hackscribble** [comment]
@ppelleti Some points to look at ...

1. The body width is 14.9mm in the elevation diagram, but your courtyard is 13.9mm wide (from -4.5 to 9.5).

2. Please check the Y position of the two NPTH mounting holes.  They are at 6.65mm in the footprint, but the drawing suggests they should be at 14.65 - 7.5 = 7.15mm.

3. The point where the chamfered side starts should be on the X axis (see image below).  In the footprint is is above the axis.

image

4. Suggest adding `power` and `DIN` to the keywords.

**Comment by ppelleti** [comment]
Thanks!  Not sure how I managed to make so many mistakes.  I believe I've now corrected all four of the issues you brought up.

**Comment by ppelleti** [comment]
revised-pd-30-footprint

**Comment by hackscribble** [comment]
Many thanks :smile:

**Pull request merged**
