### PR TITLE
Changed roundrect pads to rect

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Fix for:

https://github.com/KiCad/Connectors.pretty/pull/63#issuecomment-285805295
https://github.com/KiCad/Connectors.pretty/issues/66
https://github.com/KiCad/kicad-library/issues/1096

### CODE REVIEW

**Comment by poeschlr** [comment]
Just out of curiosity: Do you lack write permission for this repo or is it out of courtesy that you do not "merge" your own changes?

**Comment by SchrodingersGat** [comment]
It is generally accepted that we do not merge our own changes - it helps to prevent someone making a bad change because another person has to look at it :)

**Comment by poeschlr** [comment]
I looked at the footprint and i found a minor problem.
screenshot from 2017-03-11 01-39-23

I would suggest moving the pads in 0.005 in x and 0.001 in y direction
screenshot from 2017-03-11 01-39-40

Here the result of my suggested fix (as txt because i can't attach kicad_mod files)
[SMA_SMD_Jack_Straight_my_fix.txt](https://github.com/KiCad/Connectors.pretty/files/835378/SMA_SMD_Jack_Straight_my_fix.txt)

**Comment by SchrodingersGat** [comment]
Thanks, addressed :)

**Comment by jkriege2** [comment]
Thanks for the quick fix!
JAN

**Pull request merged**
