### PR TITLE
Add "thin pin" barrel jack, CUI PJ-102AH.

### PR DESCRIPTION
**Pull request by ppelleti**
This is for a "thin pin" or "breadboard friendly" barrel jack.  Although these will fit in the `BARREL_JACK.kicad_mod` footprint, the holes are much larger than they need to be, so this footprint tightens them up.  Specifically, this footprint is for the [CUI PJ-102AH](https://cdn-shop.adafruit.com/datasheets/21mmdcjackDatasheet.pdf).  However, it also fits (within 0.1 mm) a [similar product from 4UCON](https://cdn.sparkfun.com/datasheets/Prototyping/18742.pdf).

barrel-jack

### CODE REVIEW

**Comment by ppelleti** [comment]
Changed case from `BARREL_JACK_CUI_PJ-102AH` to `Barrel_Jack_CUI_PJ-102AH`, based on comment in #85.

**Comment by Shackmeister** [comment]
Hi @ppelleti can you please add a 1mm chamfer on the top left corner of the Fab square?

**Comment by ppelleti** [comment]
Sure, I've now added the chamfer.

barrel-jack-chamfer

**Comment by Shackmeister** [comment]
beautiful! :D thanks for your contribution

**Pull request merged**
