### PR TITLE
Grove 1x04

### PR DESCRIPTION
**Pull request by penoud**
Modify Grove footprint with updated link to seedstudio. Extend the layer F.Fab add a identifier for pin1 and change to 0.12 the silkscreen line width. Update link to 3d model.

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

Please have a look at our current efford to reformulate the KLCs (i.e. make them better understandable): https://github.com/SchrodingersGat/kicad-library/wiki/KLC

Here's an example for a KLC-conforming symbol (for a 6x6mm push button and an IDC receptable):
2016-12-04 22_59_49-footprinteditor keine aktive bibliothek
2017-01-15 19_20_19-library browser connect https___github com_kicad_connect pretty


Observe that 
- the component outline is on F.Fab (0.1mm thick)
- the Courtyard (only on top as the symbol is only on top) is AROUND the pads and outline of the package (F.Fab) (offset for connectors: 0.5mm)
- the Courtyard is visible AFTER assembly (so you don't really need the detailed lines below the connector. Those should be on F.Fab


Please modify your footprint along these lines ,-)

Best and thanks for all the effort you put in lately!

JAN

**Comment by penoud** [comment]
Thanks you for the explanation. I tried to change the connector according your comment. But when checking the component with the python script, I got violating 6.6 why?

**Comment by jkriege2** [comment]
Hi!

looks good already:
I think you can move the Silkscreen even closer and also the offset of the Courtyard is usually measured to the part ouline, not the silkscreen ;-) ... And the courtyards should be 0.05mm thick, not 0.1mm

Also please remove the `${KISYS3DMOD}/`-part from the 3D model, it's not necessary!

Best,
JAN

**Comment by penoud** [comment]
Hi,
I corrected the footprint according your comments.
Séb

**Comment by jkriege2** [comment]
Hi!

looks good now. THe only thing I still spotted: You have the wrong libname in the 3D module: It reads `Connect.3dshapes` but should be `Connectors.3dshapes` (sam as the .pretty-lib)!

BTW: Do you also have a PR for the 3D model?

Best,
JAN

**Comment by penoud** [comment]
Change the link to 3d model. The 3d shape is already accepted in PR #517 in kicad-library

**Comment by jkriege2** [comment]
Hi!

Hhmmm ... the PR https://github.com/KiCad/kicad-library/pull/517 was not accepted ... you closed it ... but just reopen it and I'll review ... please write a short note there where you got the model from!

JAN

**Comment by penoud** [comment]
Ok thanks I create a new PR for the 3d shape. But I didn't find inside module/package3d/Connectors.3dshapes but I found module/package3d/Connect.3dshapes where I placed my 3d package. Did I have to create the Connectors.3dshapes folder instead?

**Comment by jkriege2** [comment]
OK, I see ... that's a bug and I'll make a PR to fix it for all footprints in this lib. ;-) ...

**Pull request merged**
