### PR TITLE
2FF SMD sim card holder

### PR DESCRIPTION
**Pull request by Frankkkkk**
Following KiCad/kicad-library#909 , here is the 2FF SIM card holder module. I only put 6 pins (1,2,3,5,6,7) as pins 4 and 8 seem to never be used.

I'm not quite sure about KLC's warnings (10.2, 10.6, 6.3, 6.6) though.
Also, I don't know why but CvPcb doesn't picks it up automatically ?

First time for the footprint, sorry if it's bad… ;-)

Thanks

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi actually not bad at all!

some things should be changed:
1. You can move the CrtYd closer (0.5mm offset is enough for connectors)
2. Please add a HTTP-link to the datasheet to the Doc-field
3. Please set the attribute to SMD:
2017-01-16 08_43_47-footprint editor no active library
4. The courtyard line has to be on a 0.01mm grid

When that's changed, I'll go on with the review! for that it would also be great to have the datasheet you based this footprint on!

best,
JAN

PS: Let me know if you need further help/tips ;-)

**Comment by Frankkkkk** [comment]
Hi,
Thanks for the tips.
It's strange: in my version (4.0.5, release build), **Placement** is replaced by **Attributes** and their corresponding values (Normal, Normal+Insert, Virtual). I had to hover the mouse to see the help. Strange ;P

Anyway, it should be OK now. Thanks !

**Comment by jkriege2** [comment]
I think this might have changed since the 4.0.5-release ... You can use a nightly build to get a more current version!

About the footprint:
- The F.Fab layer should contain the actual outline of the holder, as shown in the datasheet:
2017-01-18 00_10_14-manual_simcard_top pdf - adobe acrobat reader dc
- What about the two holes in the sketch above? Are they required in the PCB???
- maybe rename the footprint to contain the company name and the name under which the company sells this thing?

Best,
JAN

**Comment by Frankkkkk** [comment]
Hi Jan,

Actually I took this datasheet because it was one that I could easily find on the internet. I did this footprint for the "chinese" 2FF SIM holders which seem to be all the same.

Thanks !
Frank
img_20170124_020016648

**Comment by hackscribble** [comment]
Closing and opening to run Travis checks again.

**Comment by hackscribble** [comment]
Posting an image of footprint for reference.

image

**Comment by hackscribble** [comment]
Hi @Frankkkkk It's been a while since your last post.  Are you still interested in contributing this footprint?

If so, as well as Jan's comments above, please take a look at the output of the Travis CI checks here: https://travis-ci.org/KiCad/Connectors.pretty/builds/258911282?utm_source=github_status&utm_medium=notification.  

 - For the warnings about KLC 7.3, 7.4 and 10.4, please refer to the latest version of the KLC here: https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention

 - On the issue about 8.2 footprint anchor, the (0,0) point of the footprint should be at the centre of the body outline that you draw on the F.Fab layer (as per Jan's comment above).  This will be different from the centre of the group of pads, since they are offset within the body.  Note: the Travis CI check will still give an error which we can ignore, since it checks pads only.

Couple of other points:

- The F.Silk outline should be visible with the part installed.  So it will need to be adjusted when you redraw the F.Fab outline.

- KLC specifies that pin 1 should be at top-left, so the footprint needs to rotate through 180 degrees.

Please do come back and ask for clarification and help if required.

**Comment by Frankkkkk** [comment]
Hi,

Thanks for your response.

I'm sorry but I haven't got time to deal with that now. Maybe in some months,

Cheers,

**Comment by Shackmeister** [comment]
@Frankkkkk 
Hey Frank
in case you want to continue with this footprint you should open a PR on this repo:
https://github.com/KiCad/Connectors_Card.pretty

**Pull request closed without merging**
