### PR TITLE
Add some more connectors

### PR DESCRIPTION
**Pull request by lkundrak**
Amphenol RJMG-3XXXX Ethernet connector
DS214B DC Barrel Jack

### CODE REVIEW

**Comment by ricardocrudo** [comment]
Hello. Do you have the part number of these components or a link to the datasheets?
Also, please, check the KLC using the michael script: https://github.com/michal777/KiCad_Lib_Check

**Comment by lkundrak** [comment]
> Hello. Do you have the part number of these components or a link to the datasheets?

Yes, they're referenced in the commit messages.

> Also, please, check the KLC using the Michal script: https://github.com/michal777/KiCad_Lib_Check

Done.

**Comment by ricardocrudo** [comment]
About RJ45_TRANSFO-2:
* I think is probably better name it as RJMGB3XXX101.
* The pinout is wrong.
* The footprint is violating the [KLC](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention)

About DS214B:
* I can't find any mechanical information in the PDF. Do you have any other part number with same characteristics?
* Also has some KLC issues.

About the name, I think Barrel_Jack_2pins would be more appropriated.
And, by the way, IMO the current BARREL_JACK could be renamed to Barrel_Jack_3pins. What do you think @michal777 ?

**Comment by michal777** [comment]
Have you any datasheets? I found only RJMG16XXXXXX1XX.pdf (not RJMG-3...)
The names could be better and the pinout of rj45 is probably wrong.
Silkscreen shouldn't cover pads and position of pin 1 should be (0, 0).

**Comment by lkundrak** [comment]
> About RJ45_TRANSFO-2:
>
>    I think is probably better name it as RJMGB3XXX101.

Ok, will rename.

>    The pinout is wrong.

I've made the pin numbers match the RJ45-TRANSFO schematic component. Is there any other way I could map the pins?

Should I create a new schematic component for that? It would be the same, only the pin numbers would differ.

>    The footprint is violating the KLC

The script didn't report any errors.

Added the courtyard and moved pin 1 to the origin.

> About DS214B:
>
 >   I can't find any mechanical information in the PDF. Do you have any other part number with same characteristics?
>    Also has some KLC issues.

Added a courtyard.

Any other issues?

> About the name, I think Barrel_Jack_2pins would be more appropriated.

Okay.

**Comment by lkundrak** [comment]
Ping?

**Comment by ricardocrudo** [comment]
pinout of RJ45 must be as indicated on datasheet.
Barrel Jack silkscreen line is superposing the pads.
@lkundrak please use now the new script to check (check_kicad_mod): https://github.com/KiCad/kicad-library-utils/tree/master/pcb
thanks.

**Comment by hackscribble** [comment]
Hi @lkundrak 

Sorry your pull request got forgotten for so long. If you are still interested in contributing, please open a new pull request (in synch with the current master branch) and check your contribution against the latest KiCad Library Convention here: https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention.

Many thanks

**Pull request closed without merging**
