### PR TITLE
Add SMA SMD connector jack (female)

### PR DESCRIPTION
**Pull request by gauravjuvekar**
Reference design from
http://www.amphenolrf.com/downloads/dl/file/id/4007/product/2974/132134_10_customer_drawing.pdf
selection_092

The multiple pads are there as I wanted to approximate an inverse-semicircular pad.

check_kicad_mod.py says that courtyard clearance should be 0.5mm, but https://github.com/SchrodingersGat/kicad-library/wiki/KLC says default should be 0.25mm

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

the clearance should be 0.5mm for connectors (KLC 7.4.iv.c). SO that is fine. Please remove the second %R-label on F.Fab ... one is enough ;-) Then I will merge!

Best,
JAN

**Comment by gauravjuvekar** [comment]
@jkriege2  Removed the %R on F.Fab

I couldn't find a 7.4.iv in the KLC linked in the first post. Where is the latest version that you are referring?

selection_094

**Comment by jkriege2** [comment]
typo ... I meant 7.5.iv.c in https://github.com/SchrodingersGat/kicad-library/wiki/KLC

**Comment by gauravjuvekar** [comment]
@jkriege2 

I've changed the clearance to be a little more than 0.5mm, but check_kicad_mod.py is still complaining that it is too small. Using the --fixmore option makes the clearance really huge in the horizontal direction.
I've checked the file in a text editor and confirmed that there are no small invisible objects around the footprint that could cause check_kicad_mod.py to increase the horizontal courtyard clearance so much.

**Comment by jkriege2** [comment]
Hi!

the courtyard-check is currently a bt buggy (especially in the Travis version and especially with rotated pads) ... so ignore those courtyard-errors if it looks OK to you (just take them as a hint to have a second look) ... 

For your symbol: Yery nice work, Thanks!

JAN

**Comment by poeschlr** [comment]
I know it is to late. But @jkriege2, @SchrodingersGat or anybody with write access:
This footprint uses a rounded rectangle!!! The current stable version can not cope with that.
https://github.com/KiCad/Connectors.pretty/issues/66

**Comment by jkriege2** [comment]
fix is merged: https://github.com/KiCad/Connectors.pretty/pull/68

**Pull request merged**
