### PR TITLE
RJ45 fix

### PR DESCRIPTION
**Pull request by leventelist**
Outline and mounting hole position fix.

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

thanks for the fixes. As you're currently at it ... could you make this KLC-conforming (https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention), i.e.:
1. add Courtyard
2. add package outline on F.Fab
3. set anchor to pin1

Rest looks good!

JAN

**Comment by leventelist** [comment]
1, 2 done. However, I can not do 3. Pin 1 is not on grid and the tool lacks pin snapping. Sorry.

**Comment by jkriege2** [comment]
Hi!

the silkscreen should be visible after assembling, so it is usually a bit offset from the F.Fab line (which reproduces the exact outline).

Here's an example:
2016-12-04 22_59_49-footprinteditor keine aktive bibliothek
2016-12-03 13_09_09-footprinteditor keine aktive bibliothek

Best,
JAN

**Comment by jkriege2** [comment]
You can fix the pin1-issue with the --fix option of the KLC-check-scripts: https://github.com/KiCad/kicad-library-utils

Best,
JAN

**Comment by jkriege2** [comment]
... but take care: the script currently tends to alter the CrtYd in a wrong way!

**Comment by leventelist** [comment]
I hope this is okay now.

**Comment by jkriege2** [comment]
Hi!

there are still some KLC violations (used out check script):
```
checking module: RJ45_8
  Violating Rule 10.2
    Doc property contains a full description of footprint.
      Documentation was empty!

  Violating Rule 6.3
    For through-hole components, footprint anchor is set on pad 1.
      pin1 was found at x=-4.445mm y=-6.35mm.
  Violating Rule 6.5
    Silkscreen is not superposed to pads, its outline is completely visible after board assembly, uses
    0.12mm line width and provides a reference mark for pin 1. (IPC-7351C).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'width': 0.15, 'start':
      {'x': -7.87, 'y': -10.47}, 'end': {'x': -7.87, 'y': 8.13}, 'layer': 'F.SilkS'}).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'width': 0.15, 'start':
      {'x': 7.87, 'y': -10.47}, 'end': {'x': -7.87, 'y': -10.47}, 'layer': 'F.SilkS'}).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'width': 0.15, 'start':
      {'x': 7.87, 'y': 8.13}, 'end': {'x': 7.87, 'y': -10.470002}, 'layer': 'F.SilkS'}).
      Some silkscreen line has a width of 0.15mm, different from 0.12mm (line: {'width': 0.15, 'start':
      {'x': -7.87, 'y': 8.13}, 'end': {'x': 7.87, 'y': 8.13}, 'layer': 'F.SilkS'}).

  Violating Rule 6.6
    Courtyard line has a width 0.05mm. This line is placed so that its clearance is measured from its
    center to the edges of pads and body, and its position is rounded on a grid of 0.01mm.
      Some courtyard line is not on the expected grid of 0.01mm (line: {'width': 0.05, 'start': {'x':
      8.12, 'y': 8.380002}, 'end': {'x': 8.12, 'y': -10.720002}, 'layer': 'F.CrtYd'}).
      Some courtyard line is not on the expected grid of 0.01mm (line: {'width': 0.05, 'start': {'x':
      8.120003, 'y': -10.72}, 'end': {'x': -8.120003, 'y': -10.72}, 'layer': 'F.CrtYd'}).
```

Plase fix them ... let me know if I can assist somehow ... I used the --fix-option of the scripts ... and this should fix most problems:
```
  (fp_line (start -3.42 -4.12) (end -3.42 14.48) (layer F.SilkS) (width 0.12))
  (fp_line (start 12.32 -4.12) (end -3.42 -4.12) (layer F.SilkS) (width 0.12))
  (fp_line (start 12.32 14.48) (end 12.32 -4.12) (layer F.SilkS) (width 0.12))
  (fp_line (start -3.42 14.48) (end 12.32 14.48) (layer F.SilkS) (width 0.12))
  (fp_line (start 12.07 -3.87) (end -3.17 -3.87) (layer F.Fab) (width 0.1))
  (fp_line (start -3.17 14.23) (end 12.07 14.23) (layer F.Fab) (width 0.1))
  (fp_line (start -3.17 -3.87) (end -3.17 14.23) (layer F.Fab) (width 0.1))
  (fp_line (start 12.07 14.23) (end 12.07 -3.87) (layer F.Fab) (width 0.1))
  (pad "" np_thru_hole circle (at 10.16 6.35) (size 3.25 3.25) (drill 3.25) (layers *.Cu *.SilkS *.Mask))
  (pad "" np_thru_hole circle (at -1.27 6.35) (size 3.25 3.25) (drill 3.25) (layers *.Cu *.SilkS *.Mask))
  (pad 1 thru_hole rect (at 0 0) (size 1.5 1.5) (drill 0.9) (layers *.Cu *.Mask F.SilkS))
  (pad 2 thru_hole circle (at 1.27 -2.54) (size 1.5 1.5) (drill 0.9) (layers *.Cu *.Mask F.SilkS))
  (pad 3 thru_hole circle (at 2.54 0) (size 1.5 1.5) (drill 0.9) (layers *.Cu *.Mask F.SilkS))
  (pad 4 thru_hole circle (at 3.81 -2.54) (size 1.5 1.5) (drill 0.9) (layers *.Cu *.Mask F.SilkS))
  (pad 5 thru_hole circle (at 5.08 0) (size 1.5 1.5) (drill 0.9) (layers *.Cu *.Mask F.SilkS))
  (pad 6 thru_hole circle (at 6.35 -2.54) (size 1.5 1.5) (drill 0.9) (layers *.Cu *.Mask F.SilkS))
  (pad 7 thru_hole circle (at 7.62 0) (size 1.5 1.5) (drill 0.9) (layers *.Cu *.Mask F.SilkS))
  (pad 8 thru_hole circle (at 8.89 -2.54) (size 1.5 1.5) (drill 0.9) (layers *.Cu *.Mask F.SilkS))
  (model Connect.3dshapes/RJ45_8.wrl
    (at (xyz 0.175 -0.25 0))
    (scale (xyz 0.4 0.4 0.4))
    (rotate (xyz 0 0 0))
  )
```

**Comment by jkriege2** [comment]
please fix conflict!

JAN

**Comment by leventelist** [comment]
On Thu, 19 Jan 2017 01:00:14 -0800
"Jan W. Krieger" <notifications@github.com> wrote:

> please fix conflict!

Sorry for the delay. I fix it in the weekend.


Lev


-- 
73 de HA5 OpenGL
Op.: Levente

**Comment by jkriege2** [comment]
Please also fix the conflict!

**Comment by leventelist** [comment]
I commited KLC fixes. However, the script still complains about 6.6. That is courtyard on 0.01mm grid and thickness of 0.05. I have them both, so I don't know why it fails.

**Comment by jkriege2** [comment]
please remove all the other kicad_mod from your PR ... where you only changed the line-endings!

ABout rule 6.6: THere the script is still a bit buggy, but to me it looks OK, so just leave it that way. 

Finally: Please add a text to the F.Fab-layer with `%R` as text ... this adds a REFDES to F.Fab!

Best,
JAN

**Comment by leventelist** [comment]
Refdes added, but I dunno how to fix this line ending issue. I'm on a Linux machine, and I bet git automatically corrected the line ending to the Unix style. I know I can somehow configure git not to do that. Sorry for the vandalism, it wasn't intentional.

**Comment by jkriege2** [comment]
About the line-endings, yes that seems to have happened ...

Have you tried deleting these files (not from the git!) and just pulling in the trunk from github.com again? Maybe that works ... I know there are some problems sometimes with line-endings and git ...

Best,
JAN

**Comment by leventelist** [comment]
Yeah... that is why I started to design a binary file format for gEDA/pcb. It was an SQLite database. Let me try what you suggest, but I don't think it should work, because git will get the missing files from its packed objects... with the UNIX line endings. So I think I better do yet another commit to fix them.

**Comment by jkriege2** [comment]
Generally we got into some of these problems since adding a .gitattributes-file with `*.kicad_mod text=auto` + the fact that some files maybe have the Windows-lineending in the Github-repo ... Hopefully we can find some way to limit this PR to that single file ... If it does not work on your side, I can take the file and open a PR from my win machine ... This PR https://github.com/KiCad/Connectors.pretty/pull/62 from me does not suffer from the same problem ...

Best,
JAN

**Comment by jkriege2** [comment]
Hi!

I just submitted a PR to fix the line-endings in the Repo https://github.com/KiCad/Connectors.pretty/pull/69 ... when it is merged, please merge the trunk into you PR and I hope the problems are solved ...

Best,
JAN

**Comment by leventelist** [comment]
Ok. The problem is that we have file: .gitattributes
In this we have this: *.kicad_mod text=auto
It overrides the the core.autocrlf setting of the user. So if you check out on linux, you'll have CR line endings. I suggest this:

*.kicad_mod text eol=crlf

Which will enforce CRLF line endings. See this:

https://help.github.com/articles/dealing-with-line-endings/

**Comment by leventelist** [comment]
Ok. I somehow fixed this, but I didn't want to merge to my own master. So I created a new branch called line_ending_fix
Could you please check it? If it is okay, I merge that to master.

**Comment by jkriege2** [comment]
Please wait for my PR from above ... with that the .gitattributes should work quite nicely and I hope it fixes out problem!

JAN

**Comment by leventelist** [comment]
I don't get this. The goal is to have UNIX line endings? So then my master branch is okay. (and fixes the rest of the footprints)

Lev

**Comment by jkriege2** [comment]
OK, my PR is merged now. If you now pull the github-master into your branch ... does it solve the problem?

Best,
JAN

**Comment by jkriege2** [comment]
BTW: Sorry for that noise ... I made a second PR to get this fixed for two reasons:
1. to check whether this works (we will also have to check some other repos for that "bug" then!
2. to keep this PR to only fixing that one RJ45: Easier to review and easier to see what changed lateron.

Hope that's OK for you.
Best,
JAN

**Comment by jkriege2** [comment]
Hi @leventelist are you still on this one?

**Comment by Shackmeister** [comment]
Hi @leventelist are you still planning on going through with this? :)

**Comment by leventelist** [comment]
On Fri, 15 Sep 2017 14:46:10 -0700
Frank Severinsen <notifications@github.com> wrote:

> Hi @leventelist are you still planning on going through with this? :)

Yes, I want to finish it. I was super busy. Could you give me an update what is missing?

Thanks,
Lev

**Comment by Shackmeister** [comment]
@leventelist Sounds great! :)
first of your branch is conflicting with practically every file in this repo :)
can you please fix this?
perhaps it would be easier to close this PR, get your branch up to date (make sure to backup your file), make a new one with the changes.
from there its gonna be much easier to do a proper review

**Comment by leventelist** [comment]
So I did a fresh fork, since my repository was messed up. I create a new PR.

**Pull request closed without merging**
