### PR TITLE
Add 8-pin SIM connector IQRF KON-SIM-01 for IQRF TR modules

### PR DESCRIPTION
**Pull request by Roman3349**
Datasheet: http://iqrf.org/weben/downloads.php?id=104
iqrf_kon-sim-01

Signed-off-by: Roman3349 <ondracek.roman@centrum.cz>

### CODE REVIEW

**Comment by Schlumpf** [comment]
Hi, if I understand it correctly, the gap at the top is coverd by the sim card, so maybe the courtyard should be a rectangle including the gap.
But I'm not a librarian ;)

**Comment by jkriege2** [comment]
I would say the same as @Schlumpf ... so could you still change that?

Thanks,
JAN

**Comment by jkriege2** [comment]
Otherwise this looks good to me and I would merge it when the last change is done!

JAN

PS: Thanks for the work you put into this!

**Comment by Roman3349** [comment]
@jkriege2 Fixed courtyard.

**Comment by jkriege2** [comment]
Oh! We meant this:
2016-12-21 19_30_19-052e950a-b607-11e6-9cf5-6008da28c468 png png-grafik 800 x 800 pixel

**Comment by Roman3349** [comment]
@jkriege2 Sorry, now it is fixed.

**Comment by jkriege2** [comment]
nice work!

thanks,
JAN

**Pull request merged**
